context:
  version: 1.12.6

package:
  name: julia
  version: ${{ version }}

source:
  - if: osx and arm64
    then:
      - url: https://julialang-s3.julialang.org/bin/mac/aarch64/1.12/julia-1.12.6-macaarch64.tar.gz
        sha256: 277d82fbd2eda99d0963b3e41f3dc979d7486f181399f8430fb637318ccd6a31
  - if: osx and x86_64
    then:
      - url: https://julialang-s3.julialang.org/bin/mac/x64/1.12/julia-1.12.6-mac64.tar.gz
        sha256: 1a70b7c606d6bac38a246e722369e5b30914dccf9378499d2712fb3bd282642c
  - if: linux and aarch64
    then:
      - url: https://julialang-s3.julialang.org/bin/linux/aarch64/1.12/julia-1.12.6-linux-aarch64.tar.gz
        sha256: 029b93b857bd0ffd627f9a8580d3bbaa63daf008d7b7aed02fbceb8fd57c4899
  - if: linux and x86_64
    then:
      - url: https://julialang-s3.julialang.org/bin/linux/x64/1.12/julia-1.12.6-linux-x86_64.tar.gz
        sha256: bbabf3bef19421a9dbd24a767d807606ab85e444323b5a1c73ffe293fa3d079a
  - if: win and x86_64
    then:
      - url: https://julialang-s3.julialang.org/bin/winnt/x64/1.12/julia-1.12.6-win64.tar.gz
        sha256: 89f9243acbbc5078863952f3b1771d9c8eb14f3f5329f54b5a73033d1a769117

build:
  script:
    - if: unix
      then:
        - cp -r $SRC_DIR/* $PREFIX/
        - rm -rf $PREFIX/LICENSE.md
    - if: win
      then:
        - robocopy %SRC_DIR% %LIBRARY_PREFIX% /E
        - del /F /Q %LIBRARY_PREFIX%\LICENSE.md

  dynamic_linking:
    binary_relocation: false

tests:
  - script:
      - julia -e 'println("Hello, world!")'
      - julia --help

about:
  homepage: https://julialang.org/
  license: MIT
  summary: Julia is a high-level, high-performance dynamic programming language for technical computing.
  license_file: LICENSE.md